title: CHIRAG BHARDWAJ # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>B.S. in Computer Science & Data Science</b>
  <br>
  UW Madison 2024
  <br><br>
  <a href="https://www.linkedin.com/in/chirag-bhardwaj-976a921b4">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
