title: <center>Chirag Bhardwaj</center> # your name (or website title) here
logo: "/images/Image1-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>B.S. in Computer Science</b>
  <br>
  UW Madison 2024
  <br><br>
  <br><br>
  I am a highly motivated Computer Science student who's passionate about learning new technologies and working on personal projects. My keen interest in the field allows me to devote time and effort into making quality software with clean and efficient code. 
  <a href="https://www.linkedin.com/in/chirag-bhardwaj-976a921b4">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/pdf/Chirag Bhardwaj.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
